default: &default
  adapter: postgresql
  encoding: unicode
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: PM_dev

test: &test
  <<: *default
  database: PM_test

production:
  <<: *default
  database: PM_production
  username: untitled
  password: <%= ENV['PM_DATABASE_PASSWORD'] %>
